In [1]:
import nibabel as nib
import numpy as  np
import os

In [2]:
img = nib.load('sub-HC001_ses-01_acq-mp2rage_T1map.nii.gz')

In [3]:
img_header = img.header
img_header

In [6]:
print(img_header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 320 320   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.  0.8 0.8 0.8 0.  0.  0.  0. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'6.0.0'
aux_file        : b''
qform_code      : scanner
sform_code      : unknown
quatern_b       : -0.06856307
quatern_c       : -0.015582562
quatern_d       : -0.019387364
qoffset_x       : -92.05724
qoffset_y       : -107.88861
qoffset_z       : -116.

In [5]:
# extract qoffsets as image origin

qoffsets_x = img_header['qoffset_x']
qoffsets_y = img_header['qoffset_y']
qoffsets_z = img_header['qoffset_z']

print(qoffsets_x, qoffsets_y, qoffsets_z)

-92.05724 -107.88861 -116.848816


In [8]:
# extracting the voxel spacing

voxel_spacing = img_header['pixdim'][1:4]

print(voxel_spacing)

[0.8 0.8 0.8]


In [9]:
# create new affine matrix 

affine = np.array([[voxel_spacing[0], 0, 0, qoffsets_x],[0, voxel_spacing[1], 0, qoffsets_y],[0, 0, voxel_spacing[2], qoffsets_z],[0, 0, 0, 1]])
print(affine) 

[[   0.80000001    0.            0.          -92.05724335]
 [   0.            0.80000001    0.         -107.88861084]
 [   0.            0.            0.80000001 -116.84881592]
 [   0.            0.            0.            1.        ]]


In [10]:
img_header['srow_x'] = affine[0,:]
img_header['srow_y'] = affine[1,:]
img_header['srow_z'] = affine[2,:]

print(img_header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 320 320   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.  0.8 0.8 0.8 0.  0.  0.  0. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'6.0.0'
aux_file        : b''
qform_code      : scanner
sform_code      : unknown
quatern_b       : -0.06856307
quatern_c       : -0.015582562
quatern_d       : -0.019387364
qoffset_x       : -92.05724
qoffset_y       : -107.88861
qoffset_z       : -116.

In [17]:
updated_img = nib.Nifti1Image(img.get_fdata(), affine, img_header)

In [18]:
nib.save(updated_img, 'sub-HC001_ses-01_acq-mp2rage_T1map_updated2.nii.gz')

In [20]:
img_updated2 = nib.load('sub-HC001_ses-01_acq-mp2rage_T1map_updated2.nii.gz')

print(img_updated2.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 320 320   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.  0.8 0.8 0.8 0.  0.  0.  0. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'6.0.0'
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -92.05724
qoffset_y       : -107.88861
qoffset_z       : -116.848816
srow_x          : [

In [21]:
sampled_img = img_updated2.slicer[::5,:,:]

In [22]:
nib.save(sampled_img, 'sub-HC001_ses-01_acq-mp2rage_T1map_updated2_sampled.nii.gz')

In [23]:
print(sampled_img.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3  48 320 320   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.  4.  0.8 0.8 1.  1.  1.  1. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'6.0.0'
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -92.05724
qoffset_y       : -107.88861
qoffset_z       : -116.848816
srow_x          : [

In [24]:
print(img_updated2.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 320 320   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.  0.8 0.8 0.8 0.  0.  0.  0. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'6.0.0'
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -92.05724
qoffset_y       : -107.88861
qoffset_z       : -116.848816
srow_x          : [

In [26]:
import tabulate

header_original = img_updated2.header.structarr
header_sampled = sampled_img.header.structarr

header_params = img.header.keys()

compare = []
for param in header_params:
    compare.append([param, header_original[param].tolist(), header_sampled[param].tolist()])

table = tabulate.tabulate(compare, tablefmt='html')

table

'<table>\n<tbody>\n<tr><td>sizeof_hdr    </td><td>348                                                                               </td><td>348                                                                 </td></tr>\n<tr><td>data_type     </td><td>b&#x27;&#x27;                                                                               </td><td>b&#x27;&#x27;                                                                 </td></tr>\n<tr><td>db_name       </td><td>b&#x27;&#x27;                                                                               </td><td>b&#x27;&#x27;                                                                 </td></tr>\n<tr><td>extents       </td><td>0                                                                                 </td><td>0                                                                   </td></tr>\n<tr><td>session_error </td><td>0                                                                                 </td><td>0                                                                   </td></tr>\n<tr><td>regular       </td><td>b&#x27;r&#x27;                                                                              </td><td>b&#x27;r&#x27;                                                                </td></tr>\n<tr><td>dim_info      </td><td>0                                                                                 </td><td>0                                                                   </td></tr>\n<tr><td>dim           </td><td>[3, 240, 320, 320, 1, 1, 1, 1]                                                    </td><td>[3, 48, 320, 320, 1, 1, 1, 1]                                       </td></tr>\n<tr><td>intent_p1     </td><td>0.0                                                                               </td><td>0.0                                                                 </td></tr>\n<tr><td>intent_p2     </td><td>0.0                                                                               </td><td>0.0                                                                 </td></tr>\n<tr><td>intent_p3     </td><td>0.0                                                                               </td><td>0.0                                                                 </td></tr>\n<tr><td>intent_code   </td><td>0                                                                                 </td><td>0                                                                   </td></tr>\n<tr><td>datatype      </td><td>16                                                                                </td><td>16                                                                  </td></tr>\n<tr><td>bitpix        </td><td>32                                                                                </td><td>32                                                                  </td></tr>\n<tr><td>slice_start   </td><td>0                                                                                 </td><td>0                                                                   </td></tr>\n<tr><td>pixdim        </td><td>[1.0, 0.800000011920929, 0.800000011920929, 0.800000011920929, 0.0, 0.0, 0.0, 0.0]</td><td>[1.0, 4.0, 0.800000011920929, 0.800000011920929, 1.0, 1.0, 1.0, 1.0]</td></tr>\n<tr><td>vox_offset    </td><td>0.0                                                                               </td><td>0.0                                                                 </td></tr>\n<tr><td>scl_slope     </td><td>nan                                                                               </td><td>nan                                                                 </td></tr>\n<tr><td>scl_inter     </td><td>nan                                                                               </td><td>nan                                                                 </td></tr>\n<tr><td>slice_end     </td><td>0                                                   

In [27]:
import nibabel

def downsample_by_slicing(input_file="", output_file="", slice_interval=1):
    # Load the high-resolution NIfTI image
    img = nibabel.load(input_file)
    data = img.get_fdata()
    affine = img.affine
    header = img.header

    # Select every nth slice in the z-dimension
    downsampled_data = data[::slice_interval, :, :]

    # Adjust the affine transformation matrix to reflect the new slice spacing
    new_affine = affine.copy()
    new_affine[0, 0] *= slice_interval  # update the z-spacing

    # Create a new NIfTI image
    new_header = header.copy()
    new_zooms = list(header.get_zooms())
    new_zooms[0] *= slice_interval  # update the z-spacing
    new_header.set_zooms(new_zooms)

    downsampled_img = nibabel.Nifti1Image(downsampled_data, affine=new_affine, header=new_header)

    # Save the downsampled image
    nibabel.save(downsampled_img, output_file)

# base_path = "C:/Users/mnwoki/Downloads/Convert nii Zip/Convert nii"
# abs_mri_high_res_img_path = os.path.join(base_path, "updated-sub-HC001_ses-01_acq-inv1_T1map.nii.gz")
# abs_mri_low_res_img_path = os.path.join(base_path, "low-updated-res-sub-HC001_ses-01_acq-inv1_T1map.nii.gz")

# downsample_by_slicing(input_file=abs_mri_high_res_img_path, output_file=abs_mri_low_res_img_path, slice_interval=5)

downsample_by_slicing(input_file='sub-HC001_ses-01_acq-mp2rage_T1map_updated2.nii.gz', output_file='sub-HC001_ses-01_acq-mp2rage_T1map_updated2_sampled_manually.nii.gz', slice_interval=5)
